# Generated by Django 4.1.5 on 2023-02-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.ImageField(max_length=40, upload_to='', verbose_name='image/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateField(verbose_name='release_dates/%Y-%m-%d/'),
        ),
    ]
